# Generated by Django 4.0.4 on 2022-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
    ]
